app/urls.py
from django.conf.urls import url
from django.views.decorators.cache import cache_page
from . import views

app_name = 'app'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    # (?P<article_id>\d+)为一个组, 其中?P<article_di>中的article_id代表了该组的组名
    # url(r'^article/(?P<article_id>\d+)$', cache_page(60 * 15)(views.ArticleDetailView.as_view()), name='detail'),
    # url(r"^category/(?P<cate_id>\d+)$", views.CategoryView.as_view(), name='category'),
    # url(r'^article/(?P<article_id>\d+)/comment/$', views.CommentView, name='comment'),
    url(r'^search/$', views.blog_search, name='search'),
    url(r'^InputImage/$', views.InputImage, name='InputImage'),
    url(r'^check/$', views.check, name='check'),
    url(r'^about_me/$', views.suggest_view, name='about_me'),
    url(r'^addImageToMNIST/$',views.addImageToMNIST,name='addImage'),
    url(r'^prediction/$', views.predictionImage, name='prediction'),
]

blog/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('app.urls')),
]

app/models.py
from django.db import models

# from django.core.urlresolvers import reverse
#
# # Create your models here.
#

#class Image(models.Model):
    # name = models.TextField
    # location = ""

# class Article(models.Model):
#     STATUS_CHOICES = (
#         ('d', 'part'),
#         ('p', 'Published'),
#     )   # 文章的状态
#
#     title = models.CharField('标题', max_length=100)
#     body = models.TextField('正文')
#
#     created_time = models.DateTimeField('创建时间', auto_now_add=True)
#     # auto_now_add : 创建时间戳，不会被覆盖
#
#     last_modified_time = models.DateTimeField('修改时间', auto_now=True)
#     # auto_now: 自动将当前时间覆盖之前时间
#
#     status = models.CharField('文章状态', max_length=1, choices=STATUS_CHOICES)
#     abstract = models.CharField('摘要', max_length=54, blank=True, null=True,
#                                 help_text="可选项，若为空格则摘取正文钱54个字符")
#     # 阅读量
#     views = models.PositiveIntegerField('浏览量', default=0)
#     # 点赞数
#     likes = models.PositiveIntegerField('点赞数', default=0)
#     # 是否置顶
#     topped = models.BooleanField('置顶', default=False)
#     # 目录分类
#     # on_delete 当指向的表被删除时，将该项设为空
#     category = models.ForeignKey('Category', verbose_name='分类',
#                                  null=True,
#                                  on_delete=models.SET_NULL)
#     # 标签云
#     tags = models.ManyToManyField('Tag', verbose_name='标签集合', blank=True)
#
#
#     def __str__(self):
#         return self.title
#
#     class Meta:
#         # Meta 包含一系列选项，这里的ordering表示排序, - 表示逆序
#         # 即当从数据库中取出文章时，以文章最后修改时间逆向排序
#         ordering = ['-last_modified_time']
#
#     def get_absolute_url(self):
#         return reverse('app:detail', kwargs={'article_id': self.pk})
#
# class Category(models.Model):
#     """
#     另外一个表,储存文章的分类信息
#     文章表的外键指向
#     """
#     name = models.CharField('类名', max_length=20)
#     created_time = models.DateTimeField('创建时间', auto_now_add=True)
#     last_modified_time = models.DateTimeField('修改时间', auto_now=True)
#
#     def __str__(self):
#         return self.name
#
# class BlogComment(models.Model):
#     user_name = models.CharField('评论者名字', max_length=100)
#     body = models.TextField('评论内容')
#     created_time = models.DateTimeField('评论发表时间', auto_now_add=True)
#     article = models.ForeignKey('Article', verbose_name='评论所属文章', on_delete=models.CASCADE)
#
#     def __str__(self):
#         return self.body[:20]
#
# class Tag(models.Model):
#     """
#     tag(标签云)对应的数据库
#     """
#     name = models.CharField('标签名', max_length=20)
#     created_time = models.DateTimeField('创建时间', auto_now_add=True)
#     last_modified_time = models.DateTimeField('修改时间', auto_now=True)
#
#     def __str__(self):
#         return self.name
#
#
# class Suggest(models.Model):
#     """
#     意见存储
#     """
#     suggest = models.TextField('意见', max_length=200)
#     suggest_time = models.DateTimeField('提出时间', auto_now_add=True)
#
#     def __str__(self):
#         return self.suggest

app/forms.py
from django import forms

#from app.models import Image


# class ImageForm(forms.ModelForm):
#     class Meta:
#         model = Image
#         name = ['name']
#         location = ['location']

app/views.py
import base64

from django.http import HttpResponse
from django.shortcuts import render
from django.views.generic.list import ListView
import logging
from app.controller.addPNGToMNIST import ImageToMNIST
from app.controller.predictionImage import predictionImage
from app.controller.toimage import base64toimg, checkimg

import json

logger = logging.getLogger(__name__)


class IndexView(ListView):
    template_name = 'blog/index.html'

    def get_queryset(self):
        """
        过滤数据，并转为html格式
        Returns:

        """
        return


def InputImage(request, ):
    print("function InputImage start:")
    print("request: ", request)
    image_data = str(request.GET['image_data'])
    tag = str(request.GET['tag'])
    # 获取图片数据
    print("tag: ", tag)
    print("image_data: ", image_data)

    strg = image_data.split(',')[1]
    result = base64toimg(strg, tag)
    return HttpResponse(result)


# 参考代码
def blog_search(request, ):
    print("function start:")
    # form = ImageForm()
    # if request.method == 'post':
    #     form = ImageForm(request.POST)

    return HttpResponse("上传成功")


# 参考代码
def suggest_view(request):
    # form = SuggestForm()
    # if request.method == 'POST':
    #     form = SuggestForm(request.POST)
    #     if form.is_valid():
    #         suggest_data = form.cleaned_data['suggest']
    #         # new_record = Suggest(suggest=suggest_data)
    #         # new_record.save()
    #         # try:
    #         #     # 使用celery并发处理邮件发送的任务
    #         #     celery_send_email.delay('访客意见', suggest_data, 'haibincoder@outlook.com', ['tomming233@163.com'])
    #         # except Exception as e:
    #         #     logger.error("邮件发送失败: {}".format(e))
    #         return redirect('app:thanks')
    return render(request, 'blog/about.html')


def addImageToMNIST(request):
    print("add start")
    result = ImageToMNIST()

    return HttpResponse(result)


def check(request, ):
    print("function InputImage start:")
    print("request: ", request)
    image_data = str(request.GET['image_data'])
    tag = str(request.GET['tag'])
    # 获取图片数据
    print("tag: ", tag)
    print("image_data: ", image_data)

    strg = image_data.split(',')[1]
    result = checkimg(strg)
    print("image path: ", result)
    response = predictionImage(result)
    return HttpResponse(response)

app/templates/blog/about.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    {% block title %}{% endblock %}

    <!-- Bootstrap Core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{% static 'css/blog-home.css' %}" rel="stylesheet">


    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>
    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'app:index' %}">主页</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="{% url 'app:about_me' %}">关于</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- jQuery -->
    <script src="{% static 'js/jquery.js' %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

app/templates/blog/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    {% block title %}{% endblock %}

    <!-- Bootstrap Core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{% static 'css/blog-home.css' %}" rel="stylesheet">

    <link href="{% static 'css/tensorflow_style.css' %}" rel="stylesheet">

    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>
    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'app:index' %}">主页</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="{% url 'app:about_me' %}">关于</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- Page Content -->
    {% block content %}{% endblock content %}

    <!-- jQuery -->
    <script src="{% static 'js/jquery.js' %}"></script>
    <script src="{% static 'js/jquery.form.js' %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

    <script src="{% static 'js/tensorflow_action.js' %}"></script>
</body>
</html>

app/templates/blog/index.html
{% extends 'blog/base.html' %}

{% block content %}
<div class="container">

    <form id="form_image" >
        <div id="div_canvas" class="row">
            <canvas id="canvas" width="280" height="280" style="background-color:black"></canvas>
            <img id="image_png" width="280" height="280" style=" background-color:black">
        </div>
        <div >
            <div class="row clearfix">
                <input id="input_tag" type="text" class="form-control django_input col-md-1" placeholder="标签"/>
                <h5 id="label_result" class="col-md-5" ></h5>
            </div>
            <div class="row clearfix">
                <button  type="button" class="btn btn-default " id="btn_upload" onclick="uploadPic();" >上传</button>
{#                <button  type="button" class="btn btn-default " onclick="train();" >训练</button>#}
                <button  type="button" class="btn btn-default " onclick="prediction();" >识别</button>
                <button  type="button" class="btn btn-default " onclick="downloadimage();" >下载</button>
                <button  type="button" class="btn btn-default " onclick="clearcanvas();" >清除</button>
            </div>
        </div>
    </form>
		<div class="row clearfix">
		<div class="col-md-12 column">
			<div class="row clearfix">
                <div class="col-md-1 column">
					<h1 class="label_num">0</h1>
					<input type="text" class="form-control txt_result" value="0.0%"/>
				</div>
				<div class="col-md-1 column">
					<h1 class="label_num">1</h1>
					<input type="text" class="form-control txt_result" value="0.0%"/>
				</div>
				<div class="col-md-1 column">
					<h1 class="label_num">2</h1>
					<input type="text" class="form-control txt_result " value="0.0%"/>
				</div>
				<div class="col-md-1 column">
					<h1 class="label_num">3</h1>
					<input type="text" class="form-control txt_result" value="0.0%"/>
				</div>
				<div class="col-md-1 column">
					<h1 class="label_num">4</h1>
					<input type="text" class="form-control txt_result" value="0.0%"/>
				</div>
				<div class="col-md-1 column">
					<h1 class="label_num">5</h1>
					<input type="text" class="form-control txt_result" value="0.0%"/>
				</div>
				<div class="col-md-1 column">
					<h1 class="label_num">6</h1>
					<input type="text" class="form-control txt_result" value="0.0%"/>
				</div>
				<div class="col-md-1 column">
					<h1 class="label_num">7</h1>
					<input type="text" class="form-control txt_result" value="0.0%"/>
				</div>
				<div class="col-md-1 column">
					<h1 class="label_num">8</h1>
					<input type="text" class="form-control txt_result" value="0.0%"/>
				</div>
				<div class="col-md-1 column">
					<h1 class="label_num">9</h1>
					<input type="text" class="form-control txt_result" value="0.0%"/>
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock content %}